package com.example.sample.domain.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;
import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Time;
import java.math.BigDecimal;

/**
 * AdminRole admin_roles
 * generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>
 *
 * @author unknown
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Data
@SuppressWarnings("unused")
public class AdminRole implements Serializable {

    private static final long serialVersionUID = 8175885627927686934L;

     
    /**
     * id id
     */
    private Integer id;
    
    /**
     * name name
     */
    private String name;
    
    /**
     * slug slug
     */
    private String slug;
    
    /**
     * createdAt created_at
     */
    private Timestamp createdAt;
    
    /**
     * updatedAt updated_at
     */
    private Timestamp updatedAt;
     
}