package com.example.sample.domain.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;
import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Time;
import java.math.BigDecimal;

/**
 * Article article
 * generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>
 *
 * @author unknown
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Data
@SuppressWarnings("unused")
public class Article implements Serializable {

    private static final long serialVersionUID = 8117147573751819949L;

     
    /**
     * id id
     */
    private Long id;
    
    /**
     * userId 用户id
     */
    private Long userId;
    
    /**
     * content 正文
     */
    private String content;
    
    /**
     * createTime 创建时间
     */
    private Timestamp createTime;
    
    /**
     * updateTime 更新时间
     */
    private Timestamp updateTime;
     
}