package com.example.sample.domain.entity;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;
import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.sql.Time;
import java.math.BigDecimal;

/**
 * QrtzSimpropTrigger QRTZ_SIMPROP_TRIGGERS
 * generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>
 *
 * @author unknown
 */
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
@Data
@SuppressWarnings("unused")
public class QrtzSimpropTrigger implements Serializable {

    private static final long serialVersionUID = 8465890331341740876L;

     
    /**
     * schedName SCHED_NAME
     */
    private String schedName;
    
    /**
     * triggerName TRIGGER_NAME
     */
    private String triggerName;
    
    /**
     * triggerGroup TRIGGER_GROUP
     */
    private String triggerGroup;
    
    /**
     * strProp1 STR_PROP_1
     */
    private String strProp1;
    
    /**
     * strProp2 STR_PROP_2
     */
    private String strProp2;
    
    /**
     * strProp3 STR_PROP_3
     */
    private String strProp3;
    
    /**
     * intProp1 INT_PROP_1
     */
    private Integer intProp1;
    
    /**
     * intProp2 INT_PROP_2
     */
    private Integer intProp2;
    
    /**
     * longProp1 LONG_PROP_1
     */
    private Long longProp1;
    
    /**
     * longProp2 LONG_PROP_2
     */
    private Long longProp2;
    
    /**
     * decProp1 DEC_PROP_1
     */
    private BigDecimal decProp1;
    
    /**
     * decProp2 DEC_PROP_2
     */
    private BigDecimal decProp2;
    
    /**
     * boolProp1 BOOL_PROP_1
     */
    private String boolProp1;
    
    /**
     * boolProp2 BOOL_PROP_2
     */
    private String boolProp2;
     
}