package entity
// generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>

import (
	"time"
	"database/sql"
)

// AdminRole admin_roles
type AdminRole struct {  
	Id uint32 `json:"id" db:"id"`  // id 
	Name string `json:"name" db:"name"`  // name 
	Slug string `json:"slug" db:"slug"`  // slug 
	CreatedAt sql.NullString `json:"created_at" db:"created_at"`  // created_at 
	UpdatedAt sql.NullString `json:"updated_at" db:"updated_at"`  // updated_at  
}
