# generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>
# AdminRole admin_roles
class AdminRole(object):
    """
    init( 
        id id
        name name
        slug slug
        created_at created_at
        updated_at updated_at 
    )
    """
    def __init__(self , id, name, slug, created_at, updated_at):
        self.id = id
        self.name = name
        self.slug = slug
        self.created_at = created_at
        self.updated_at = updated_at