# generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>
# QrtzSimpropTrigger QRTZ_SIMPROP_TRIGGERS
class QrtzSimpropTrigger(object):
    """
    init( 
        SCHED_NAME SCHED_NAME
        TRIGGER_NAME TRIGGER_NAME
        TRIGGER_GROUP TRIGGER_GROUP
        STR_PROP_1 STR_PROP_1
        STR_PROP_2 STR_PROP_2
        STR_PROP_3 STR_PROP_3
        INT_PROP_1 INT_PROP_1
        INT_PROP_2 INT_PROP_2
        LONG_PROP_1 LONG_PROP_1
        LONG_PROP_2 LONG_PROP_2
        DEC_PROP_1 DEC_PROP_1
        DEC_PROP_2 DEC_PROP_2
        BOOL_PROP_1 BOOL_PROP_1
        BOOL_PROP_2 BOOL_PROP_2 
    )
    """
    def __init__(self , SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, STR_PROP_1, STR_PROP_2, STR_PROP_3, INT_PROP_1, INT_PROP_2, LONG_PROP_1, LONG_PROP_2, DEC_PROP_1, DEC_PROP_2, BOOL_PROP_1, BOOL_PROP_2):
        self.SCHED_NAME = SCHED_NAME
        self.TRIGGER_NAME = TRIGGER_NAME
        self.TRIGGER_GROUP = TRIGGER_GROUP
        self.STR_PROP_1 = STR_PROP_1
        self.STR_PROP_2 = STR_PROP_2
        self.STR_PROP_3 = STR_PROP_3
        self.INT_PROP_1 = INT_PROP_1
        self.INT_PROP_2 = INT_PROP_2
        self.LONG_PROP_1 = LONG_PROP_1
        self.LONG_PROP_2 = LONG_PROP_2
        self.DEC_PROP_1 = DEC_PROP_1
        self.DEC_PROP_2 = DEC_PROP_2
        self.BOOL_PROP_1 = BOOL_PROP_1
        self.BOOL_PROP_2 = BOOL_PROP_2