<?php

namespace App\Models;

/**
 * Article article
 *
 * generated by ddl-to-object <https://github.com/ycrao/ddl-to-object>
 *  
 * @property integer $id id 
 * @property integer $user_id 用户id 
 * @property string $content 正文 
 * @property mixed|string $create_time 创建时间 
 * @property mixed|string $update_time 更新时间  
 * @author unknown
 */
class Article {

 
    /**
     * @var integer - id
     */
    private $id = null;

    /**
     * @var integer - 用户id
     */
    private $user_id = null;

    /**
     * @var string - 正文
     */
    private $content = null;

    /**
     * @var mixed|string - 创建时间
     */
    private $create_time = null;

    /**
     * @var mixed|string - 更新时间
     */
    private $update_time = null;


    /**
     * construct from object or array
     *
     * @param object|array $object
     * @return void
     */
    public function __construct($object = null) {
        if (is_array($object) || is_object($object)) {
            foreach ($object as $key => $value) {
                $this->$key = $value;
            }
        }
    }


    /**
     * magic get
     *
     * @param property name $key
     * @return mixed
     */
    public function __get($key) {
        return $this->$key;
    }

    /**
     * magic set
     *
     * @param property name $key
     * @param property value $value
     * @return boolean
     */
    public function __set($key, $value) {
        if (property_exists($this, $key)) {
            $this->$key = $value;
            return true;
        }
        return false;
    }
}